
# trigger: 
#   branches:
#     include:
#     - main
#     - feature/**
trigger: none
pool: MyAgentPool

stages:
- stage: Build
  displayName: Build
  jobs:
   - job: Build
     displayName: Build
     steps:
      - task: Npm@1
        displayName: npm install
        inputs:
          command: 'install'
          workingDir: '$(System.DefaultWorkingDirectory)'
      - task: Npm@1
        displayName: npm run build
        inputs:
          command: 'custom'
          workingDir: '$(System.DefaultWorkingDirectory)'
          customCommand: 'run build'

      - task: PublishBuildArtifacts@1
        displayName: Publish Build Artifacts
        inputs:
          PathtoPublish: '$(System.DefaultWorkingDirectory)/build'
          ArtifactName: 'build'
          publishLocation: 'Container'

- stage: Deploy
  displayName: Deploy
  jobs:
   - deployment: DeployToStaging
     displayName: Deploy To Staging

     environment:
      name: Staging
      resourceType: VirtualMachine

     strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: build

          - script: |
              sudo cp -r $(Pipeline.Workspace)/build/* /var/www/html/
            displayName: Copy website files
   
  #  - deployment: DeployToQA
  #    displayName: Deploy To QA

  #    environment:
  #     name: QA
  #     resourceType: VirtualMachine

  #    strategy:
  #     runOnce:
  #       deploy:
  #         steps:
  #         - download: current
  #           artifact: build

  #         - script: |
  #             sudo cp -r $(Pipeline.Workspace)/build/* /var/www/html/
  #           displayName: Copy website files
   
  #  - deployment: DeployToProduction
  #    displayName: Deploy To Production

  #    environment:
  #     name: Production
  #     resourceType: VirtualMachine

  #    strategy:
  #     runOnce:
  #       deploy:
  #         steps:
  #         - download: current
  #           artifact: build

  #         - script: |
  #             sudo cp -r $(Pipeline.Workspace)/build/* /var/www/html/
  #           displayName: Copy website files
